"""
Base Trading Bot with Self-Learning Capabilities

Each bot:
- Analyzes market data using its unique strategy
- Generates signals with confidence levels
- Tracks its own performance
- Learns from wins/losses to improve
- Shares insights with the ensemble
"""

from __future__ import annotations

import json
import os
import sys
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import hashlib

# Import index config from shared engine
try:
    _PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
    if str(_PROJECT_ROOT) not in sys.path:
        sys.path.insert(0, str(_PROJECT_ROOT))
    from shared_project_engine.indices import INDEX_CONFIG, ACTIVE_INDICES
    _INDEX_STRIKE_GAPS = {name: cfg["strike_gap"] for name, cfg in INDEX_CONFIG.items()}
    _INDEX_LOT_SIZES = {name: cfg["lot_size"] for name, cfg in INDEX_CONFIG.items()}
except ImportError:
    _INDEX_STRIKE_GAPS = {"NIFTY50": 50, "BANKNIFTY": 100, "FINNIFTY": 50, "SENSEX": 100, "MIDCPNIFTY": 25}
    _INDEX_LOT_SIZES = {"NIFTY50": 25, "BANKNIFTY": 15, "FINNIFTY": 25, "SENSEX": 10, "MIDCPNIFTY": 50}
    ACTIVE_INDICES = ["SENSEX", "NIFTY50", "BANKNIFTY", "FINNIFTY"]


def get_strike_gap(index: str) -> int:
    """Get strike gap for an index from shared config."""
    return _INDEX_STRIKE_GAPS.get(index, 50)


def get_lot_size(index: str) -> int:
    """Get lot size for an index from shared config."""
    return _INDEX_LOT_SIZES.get(index, 50)


class SignalType(Enum):
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    NEUTRAL = "NEUTRAL"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


class OptionType(Enum):
    CE = "CE"
    PE = "PE"
    NONE = "NONE"


@dataclass
class BotSignal:
    """Signal generated by a bot"""
    bot_name: str
    index: str
    signal_type: SignalType
    option_type: OptionType
    confidence: float  # 0-100
    strike: Optional[int] = None
    entry: Optional[float] = None
    target: Optional[float] = None
    stop_loss: Optional[float] = None
    reasoning: str = ""
    factors: Dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class BotDecision:
    """Final decision from ensemble"""
    action: str  # BUY_CE, BUY_PE, NO_TRADE
    index: str
    strike: Optional[int]
    entry: Optional[float]
    target: Optional[float]
    stop_loss: Optional[float]
    confidence: float
    contributing_bots: List[str]
    consensus_level: float  # % of bots agreeing
    reasoning: str
    individual_signals: List[BotSignal]


@dataclass
class TradeRecord:
    """Record of a completed trade for learning"""
    trade_id: str
    bot_name: str
    index: str
    option_type: str
    strike: int
    entry_price: float
    exit_price: float
    entry_time: str
    exit_time: str
    pnl: float
    pnl_pct: float
    outcome: str  # WIN, LOSS, BREAKEVEN
    market_conditions: Dict[str, Any]
    bot_reasoning: str
    lessons_learned: List[str] = field(default_factory=list)


@dataclass
class BotPerformance:
    """Performance metrics for a bot"""
    bot_name: str
    total_signals: int = 0
    total_trades: int = 0
    wins: int = 0
    losses: int = 0
    breakeven: int = 0
    total_pnl: float = 0.0
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    profit_factor: float = 0.0
    best_index: str = ""
    worst_index: str = ""
    best_conditions: List[str] = field(default_factory=list)
    worst_conditions: List[str] = field(default_factory=list)
    weight: float = 1.0  # Ensemble weight based on performance


class SharedMemory:
    """
    Shared knowledge base for all bots

    Stores:
    - Market patterns that worked
    - Conditions to avoid
    - Cross-bot learnings
    - Performance history
    """

    DEFAULT_DATA_DIR = Path(__file__).resolve().parents[1] / "data" / "bots"

    def __init__(self, data_dir: str = None):
        self.data_dir = Path(data_dir or os.getenv(
            "BOT_DATA_DIR",
            str(self.DEFAULT_DATA_DIR)
        ))
        self.data_dir.mkdir(parents=True, exist_ok=True)

        self.knowledge_file = self.data_dir / "shared_knowledge.jsonl"
        self.performance_file = self.data_dir / "bot_performance.json"
        self.trades_file = self.data_dir / "trade_history.jsonl"

        self._knowledge_cache: List[Dict] = []
        self._performance_cache: Dict[str, BotPerformance] = {}
        self._load_data()

    def _load_data(self):
        """Load existing data from files"""
        # Load knowledge
        if self.knowledge_file.exists():
            with open(self.knowledge_file, "r") as f:
                for line in f:
                    if line.strip():
                        try:
                            self._knowledge_cache.append(json.loads(line))
                        except json.JSONDecodeError:
                            pass

        # Load performance
        if self.performance_file.exists():
            with open(self.performance_file, "r") as f:
                try:
                    data = json.load(f)
                    for name, perf in data.items():
                        self._performance_cache[name] = BotPerformance(**perf)
                except (json.JSONDecodeError, TypeError):
                    pass

    def save_knowledge(self, knowledge: Dict[str, Any]):
        """Save a piece of knowledge to shared memory"""
        knowledge["timestamp"] = datetime.now().isoformat()
        self._knowledge_cache.append(knowledge)

        with open(self.knowledge_file, "a") as f:
            f.write(json.dumps(knowledge) + "\n")

    def get_knowledge(self, topic: str = None, limit: int = 50) -> List[Dict]:
        """Retrieve knowledge, optionally filtered by topic"""
        if topic:
            filtered = [k for k in self._knowledge_cache if topic.lower() in k.get("topic", "").lower()]
            return filtered[-limit:]
        return self._knowledge_cache[-limit:]

    def update_performance(self, bot_name: str, performance: BotPerformance):
        """Update a bot's performance metrics"""
        self._performance_cache[bot_name] = performance

        # Save all performance data
        data = {name: asdict(perf) for name, perf in self._performance_cache.items()}
        with open(self.performance_file, "w") as f:
            json.dump(data, f, indent=2)

    def get_performance(self, bot_name: str) -> Optional[BotPerformance]:
        """Get a bot's performance metrics"""
        return self._performance_cache.get(bot_name)

    def get_all_performance(self) -> Dict[str, BotPerformance]:
        """Get all bots' performance"""
        return self._performance_cache.copy()

    def record_trade(self, trade: TradeRecord):
        """Record a completed trade"""
        with open(self.trades_file, "a") as f:
            f.write(json.dumps(asdict(trade)) + "\n")

    def get_trades(self, bot_name: str = None, limit: int = 100) -> List[TradeRecord]:
        """Get trade history"""
        trades = []
        if self.trades_file.exists():
            with open(self.trades_file, "r") as f:
                for line in f:
                    if line.strip():
                        try:
                            trade = TradeRecord(**json.loads(line))
                            if bot_name is None or trade.bot_name == bot_name:
                                trades.append(trade)
                        except (json.JSONDecodeError, TypeError):
                            pass
        return trades[-limit:]

    def get_best_conditions(self, signal_type: SignalType) -> List[Dict]:
        """Get market conditions that historically worked best for a signal type"""
        return [
            k for k in self._knowledge_cache
            if k.get("type") == "winning_condition"
            and k.get("signal_type") == signal_type.value
        ]

    def get_avoid_conditions(self) -> List[Dict]:
        """Get conditions that should be avoided"""
        return [k for k in self._knowledge_cache if k.get("type") == "avoid_condition"]


class TradingBot(ABC):
    """
    Abstract base class for all trading bots

    Each bot must implement:
    - analyze(): Analyze market data and return signal
    - learn(): Learn from trade outcomes
    """

    def __init__(
        self,
        name: str,
        description: str,
        shared_memory: Optional[SharedMemory] = None
    ):
        self.name = name
        self.description = description
        self.memory = shared_memory or SharedMemory()

        # Bot-specific parameters that can be tuned
        self.parameters: Dict[str, Any] = {}

        # Performance tracking
        self.performance = self.memory.get_performance(name) or BotPerformance(bot_name=name)

        # Recent signals for tracking
        self.recent_signals: List[BotSignal] = []

    @abstractmethod
    def analyze(
        self,
        index: str,
        market_data: Dict[str, Any],
        option_chain: Optional[List[Dict]] = None
    ) -> Optional[BotSignal]:
        """
        Analyze market data and generate a signal

        Args:
            index: Index name (NIFTY50, BANKNIFTY, etc.)
            market_data: Current market data including price, change%, volume
            option_chain: Option chain data if available

        Returns:
            BotSignal if there's a trading opportunity, None otherwise
        """
        pass

    @abstractmethod
    def learn(self, trade: TradeRecord):
        """
        Learn from a completed trade

        Args:
            trade: Record of the completed trade with outcome
        """
        pass

    def get_weight(self) -> float:
        """Get this bot's weight in ensemble decisions"""
        return self.performance.weight

    def update_performance(self, trade: TradeRecord):
        """Update performance metrics after a trade"""
        self.performance.total_trades += 1

        if trade.outcome == "WIN":
            self.performance.wins += 1
            self.performance.total_pnl += trade.pnl
        elif trade.outcome == "LOSS":
            self.performance.losses += 1
            self.performance.total_pnl += trade.pnl
        else:
            self.performance.breakeven += 1

        # Calculate win rate
        if self.performance.total_trades > 0:
            self.performance.win_rate = (
                self.performance.wins / self.performance.total_trades * 100
            )

        # Calculate average win/loss
        wins = [t for t in self.memory.get_trades(self.name) if t.outcome == "WIN"]
        losses = [t for t in self.memory.get_trades(self.name) if t.outcome == "LOSS"]

        if wins:
            self.performance.avg_win = sum(t.pnl for t in wins) / len(wins)
        if losses:
            self.performance.avg_loss = sum(t.pnl for t in losses) / len(losses)

        # Calculate profit factor
        gross_profit = sum(t.pnl for t in wins) if wins else 0
        gross_loss = abs(sum(t.pnl for t in losses)) if losses else 1
        self.performance.profit_factor = gross_profit / gross_loss if gross_loss > 0 else 0

        # Adjust weight based on performance
        self._adjust_weight()

        # Save to shared memory
        self.memory.update_performance(self.name, self.performance)

    def _adjust_weight(self):
        """Adjust bot's ensemble weight based on recent performance"""
        # Base weight on win rate and profit factor
        if self.performance.total_trades < 5:
            # Not enough trades to judge
            self.performance.weight = 1.0
        else:
            # Weight formula: win_rate * profit_factor, normalized
            raw_weight = (self.performance.win_rate / 100) * max(0.5, min(2.0, self.performance.profit_factor))
            self.performance.weight = max(0.1, min(2.0, raw_weight))

    def save_learning(self, topic: str, insight: str, conditions: Dict[str, Any] = None):
        """Save a learning insight to shared memory"""
        self.memory.save_knowledge({
            "bot": self.name,
            "topic": topic,
            "insight": insight,
            "conditions": conditions or {},
            "type": "learning"
        })

    def get_relevant_learnings(self, index: str, market_conditions: Dict) -> List[Dict]:
        """Get learnings relevant to current market conditions"""
        all_knowledge = self.memory.get_knowledge(limit=100)

        # Filter for relevant knowledge
        relevant = []
        for k in all_knowledge:
            # Check if from this bot or tagged as universal
            if k.get("bot") == self.name or k.get("universal", False):
                # Check if conditions match
                k_conditions = k.get("conditions", {})
                if self._conditions_match(k_conditions, market_conditions):
                    relevant.append(k)

        return relevant[-10:]  # Return most recent relevant learnings

    def _conditions_match(self, stored: Dict, current: Dict) -> bool:
        """Check if stored conditions match current market conditions"""
        if not stored:
            return True

        # Check key conditions
        for key in ["trend", "volatility", "session"]:
            if key in stored and key in current:
                if stored[key] != current[key]:
                    return False

        return True

    def generate_trade_id(self, index: str, option_type: str, strike: int) -> str:
        """Generate unique trade ID"""
        data = f"{self.name}_{index}_{option_type}_{strike}_{datetime.now().isoformat()}"
        return hashlib.md5(data.encode()).hexdigest()[:12]

    def to_dict(self) -> Dict[str, Any]:
        """Convert bot state to dictionary"""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": self.parameters,
            "performance": asdict(self.performance),
            "recent_signals": [asdict(s) for s in self.recent_signals[-10:]],
        }
